#print text
print("Hi")
print("I am learning Python")
print("It is good")
print("nice try")
print("good job")
print('Hi')
print('This is also gonna work')
print('adsawd')
print('asdasdsda')
print('awdawdawd')
print('Also it is possible to change the end parameter', end='         ')
print("It is all on one line", end="//||\\")
print("equal", end='=')
print(500, end="tenge")
print("the final", end="!!!")
#print numbers
print(25,end="!=")
print(24, end="!=")
print(198+25)
print(2*6)
print(256/8)
print("Hello, im",20, "years old!" )
print("2+5=", 2+5)
print("nice weather=",+23,"celsius")
print("25/5=", 25/5)
print("the final 50+50=", 100)