import datetime

print(datetime.datetime.now())
x = datetime.datetime.now()
print(x)
now = datetime.datetime.now()
print(now)
print(datetime.datetime.now().date())
print(datetime.datetime.now().time())

x = datetime.datetime.now()
print(x.year)
x = datetime.datetime.now()
print(x.month)
x = datetime.datetime.now()
print(x.day)
x = datetime.datetime.now()
print(x.strftime("%A"))
x = datetime.datetime.now()
print(x.strftime("%w"))

x = datetime.datetime(2020, 5, 17)
print(x)
x = datetime.datetime(2021, 1, 1)
print(x)
x = datetime.datetime(2022, 12, 31)
print(x)
x = datetime.datetime(2023, 6, 15, 10, 30)
print(x)
x = datetime.datetime(2024, 2, 29)
print(x)

x = datetime.datetime(2018, 6, 1)
print(x.strftime("%B"))
x = datetime.datetime(2018, 6, 1)
print(x.strftime("%b"))
x = datetime.datetime(2018, 6, 1)
print(x.strftime("%Y"))
x = datetime.datetime(2018, 6, 1)
print(x.strftime("%d"))
x = datetime.datetime(2018, 6, 1)
print(x.strftime("%Y-%m-%d"))

x = datetime.datetime.now()
print(x.strftime("%H"))
x = datetime.datetime.now()
print(x.strftime("%M"))
x = datetime.datetime.now()
print(x.strftime("%S"))
x = datetime.datetime.now()
print(x.strftime("%p"))
x = datetime.datetime.now()
print(x.strftime("%c"))